# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My Take on World Via Numbers!
description: Hi, I am Won Suh, data scientist by most days, avid golfer and skiier.
  I like to think a lot of things in numbers, as I believe numbers are
  almost always probably approximately correct, and the first principal component
  of life!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://won782.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github: won782
repository: won782/won782.github.io
name: Won Suh

# Site Author
author:
 name : *name
 avatar : "/assets/img/won.jpg"
 location : "Boston, MA"
 email : won782@gmail.com
 uri : "https://won782.github.io"
 home : "https://won782.github.io"
 github : "won782"
 linkedin : "won782"
 stackoverflow : "https://stackoverflow.com/users/3893584/won782"
 bio : "Numbers, Data, Cracking, and Occasional Travels"




# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-feed
  - jekyll-crosspost-to-medium


