# 'LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8" bundle exec jekyll serve -H 0.0.0.0 --incremental --watc'

title: Won Take on World
title_separator: "-"
description: Personal Webpage of Won Suh
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://won782.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github: won782
repository: won782/won782.github.io
name: Won Suh

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      read_time: true
      layout: single
      related: true
      share: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _numbers
  - scope:
      path: ""
      type: numbers
    values:
      author_profile: true
      read_time: true
      layout: single
      related: true
      share: true
  # _extracurriculars
  - scope:
      path: ""
      type: extracurriculars
    values:
      author_profile: true
      read_time: true
      layout: single
      related: true
      share: true


# Site Author
author:
 name : *name
 avatar : "/assets/img/avatar.png"
 location : "Boston, MA"
 email : won782@gmail.com
 uri : "https://won782.github.io"
 home : "https://won782.github.io"
 github : "won782"
 linkedin : "won782"
 stackoverflow : "3893584/won782"
 bio :  "Believer in number as first principal component of the world, or a boring guy - Minus being Thinker, Golfer, Solider, and Skiier"

# Optionals
words_per_minute: 200



# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-feed
  - jekyll-crosspost-to-medium
  - jekyll-redirect-from
include: ["_pages", "_numbers", "_extracurriculars"]

# Configure pagination
paginate: 5
paginate_path: /page:num/

# Enable collections
collections:
  numbers:
    output: true
    permalink: /:collection/:path
  extracurriculars:
    output: true
    permalink: /:collection/:path